global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            my_database: lib/data/local/db/app_database.dart
          schema_dir: lib/data/local/db/entity
          store_date_time_values_as_text: true # (default false for Unix timestamps)
         
